require("core.autocmds")
require("core.keymaps")
require("core.options")

require("pack")

require("plugins.autopairs")
require("plugins.blink")
require("plugins.colorscheme")
require("plugins.indentscope")
require("plugins.lazygit")
require("plugins.mason")
require("plugins.neotree")
require("plugins.nvim-lspconfig")
require("plugins.telescope")
require("plugins.tree-sitter-manager")
require("plugins.undotree")
